/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang /home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/matmul.cpp -foptimization-record-file=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/clang.matmul.cpp.diag.yml -mllvm -pass-remarks-missed="reflow|pasta|unroll" -mllvm -pass-remarks="reflow|pasta|unroll|inline" -fno-limit-debug-info -gcc-toolchain /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/tps/lnx64/gcc-6.2.0 -fhls -fno-exceptions -E -fno-math-errno -c -emit-llvm -mllvm -disable-llvm-optzns -Werror=implicit-function-declaration -Werror=implicit-hls-streams -Werror=return-type -Wpragmas -Wunused-parameter -fno-threadsafe-statics -fno-use-cxa-atexit -std=gnu++14 -target fpga64-xilinx-linux-gnu -fno-threadsafe-statics -fno-use-cxa-atexit -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot/ -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot/39 -D__VITIS_HLS__ -DAESL_SYN -D__SYNTHESIS__ -D__HLS_SYN__ -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot/ap_sysc -include etc/autopilot_ssdm_op.h -D__DSP48E1__ -I /usr/include/x86_64-linux-gnu -o matmul.pp.0.cpp -hls-platform-db-name=/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/xilinx/common/platform.db -hls-platform-name=artix7_fast

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang -foptimization-record-file=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/clang.diag.yml -mllvm -pass-remarks-missed="reflow|pasta|unroll" -mllvm -pass-remarks="reflow|pasta|unroll|inline" -fsyntax-only -fhls -target fpga64-xilinx-linux-gnu matmul.pp.0.cpp -hls-platform-db-name=/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/xilinx/common/platform.db -hls-platform-name=artix7_fast

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang-tidy -header-filter=.* --checks=-*,xilinx-systemc-detector -import-directive=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/.systemc_flag -fix-errors matmul.pp.0.cpp -- -std=gnu++14 -target fpga -fhls -ferror-limit=0

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang-tidy -header-filter=.* --checks=-*,xilinx-directive2pragma -import-directive=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/all.directive.json -fix-errors matmul.pp.0.cpp -- -std=gnu++14 -target fpga -fhls -ferror-limit=0

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang-tidy -header-filter=.* --checks=-*,xilinx-constantarray-param,xilinx-remove-assert -fix-errors matmul.pp.0.cpp -- -std=gnu++14 -target fpga -fhls -ferror-limit=0

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang-tidy -export-fixes=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/clang-tidy.matmul.pp.0.cpp.diag.yml -header-filter=.* --checks=-*,xilinx-label-all-loops,xilinx-aggregate-on-hls-vector,,xilinx-warn-mayneed-no-ctor-attribute -fix-errors matmul.pp.0.cpp -- -std=gnu++14 -target fpga -fhls -ferror-limit=0

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/xilinx-dataflow-lawyer -export-fixes=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/xilinx-dataflow-lawyer.matmul.pp.0.cpp.diag.yml matmul.pp.0.cpp -- -std=gnu++14 -target fpga -fhls -ferror-limit=0 -fstrict-dataflow

#/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang -foptimization-record-file=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/clang.matmul.pp.0.cpp.diag.yml -mllvm -pass-remarks-missed="reflow|pasta|unroll" -mllvm -pass-remarks="reflow|pasta|unroll|inline" -fno-limit-debug-info -fhls -flto -fno-exceptions -Wno-error=c++11-narrowing matmul.pp.0.cpp -fno-math-errno -c -emit-llvm -mllvm -disable-llvm-optzns -Werror=implicit-function-declaration -Werror=implicit-hls-streams -Werror=return-type -Wpragmas -Wunused-parameter -fno-threadsafe-statics -fno-use-cxa-atexit -std=gnu++14 -target fpga64-xilinx-linux-gnu -D__VITIS_HLS__ -DAESL_SYN -D__SYNTHESIS__ -D__HLS_SYN__ -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot/ap_sysc -include etc/autopilot_ssdm_op.h -D__DSP48E1__ -g -o matmul.bc -hls-platform-db-name=/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/xilinx/common/platform.db -hls-platform-name=artix7_fast

/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/lnx64/tools/clang-3.9-csynth/bin/clang -foptimization-record-file=/home/mlevental/dev_projects/torch-mlir/hls/scripts/vitis_stuff/proj/solution1/.autopilot/db/clang.matmul.pp.0.cpp.diag.yml -mllvm -pass-remarks-missed="" -mllvm -pass-remarks="" -fno-limit-debug-info -fhls -flto -fno-exceptions -Wno-error=c++11-narrowing matmul.pp.0.cpp -fno-math-errno -c -emit-llvm -mllvm -disable-llvm-optzns -Werror=implicit-function-declaration -Werror=implicit-hls-streams -Werror=return-type -Wpragmas -Wunused-parameter -fno-threadsafe-statics -fno-use-cxa-atexit -std=gnu++14 -target fpga64-xilinx-linux-gnu -D__VITIS_HLS__ -DAESL_SYN -D__SYNTHESIS__ -D__HLS_SYN__ -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot -I /home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/autopilot/ap_sysc -include etc/autopilot_ssdm_op.h -D__DSP48E1__ -g -o matmul.bc -hls-platform-db-name=/home/mlevental/dev_projects/Xilinx_vitis/Vitis_HLS/2021.1/common/technology/xilinx/common/platform.db -hls-platform-name=artix7_fast
